/**
 * Script de migración V1: Creación de la tabla de precios e índices.
 */

CREATE TABLE prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    price_list INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL
);

-- ÍNDICE CRÍTICO: Optimización de la consulta principal.
-- En empresas con millones de registros, este índice permite búsquedas en milisegundos
-- al cubrir los campos de filtrado (productId, brandId) y el rango de fechas.
CREATE INDEX idx_prices_query ON prices (product_id, brand_id, start_date, end_date, priority DESC);